version: 2

updates:
  # Python
  - package-ecosystem: "uv"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
      day: "friday"
      time: "14:00"
      timezone: "America/Los_Angeles"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
      day: "friday"
      time: "14:00"
      timezone: "America/Los_Angeles"

  # NodeJS
  - package-ecosystem: "npm"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
      day: "friday"
      time: "14:00"
      timezone: "America/Los_Angeles"
